name: CI
on: [push, pull_request]

permissions:
    contents: read #  to fetch code (actions/checkout)

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_version: '8.1'
            -   name: Run PHP-CS-Fixer
                run: vendor/bin/php-cs-fixer fix --dry-run --diff --allow-risky=yes

    phpstan:
        name: PHPStan
        needs: php-cs-fixer
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_version: '8.1'
            -   name: Run PHPStan
                uses: php-actions/phpstan@v3
                with:
                    php_version: '8.1'

    tests:
        name: Tests
        needs: phpstan
        timeout-minutes: 10
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
            -   name: Composer Install
                run: composer install --no-interaction --no-cache
            -   name: PHPUnit
                run: vendor/bin/phpunit
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                php-version: ['8.1', '8.2', '8.3', '8.4']

    tests-without-bcmath:
        name: Tests (without BCMath extension)
        needs: phpstan
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: :bcmath # ubuntu only
            -   name: Composer Install
                run: composer install --no-interaction --no-cache
            -   name: PHPUnit (without BCMath extension)
                run: vendor/bin/phpunit --group without-bcmath
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.1', '8.2', '8.3', '8.4']
