name: PHP-src BCMath Tests

on: [push, pull_request]

jobs:
  php-src-bcmath-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.4']

    steps:
    - uses: actions/checkout@v5

    - name: Checkout php-src repository
      uses: actions/checkout@v5
      with:
        repository: php/php-src
        path: php-src

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: :bcmath
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Prepare php-src BCMath tests
      run: |
        mkdir -p tests/php-src
        cp php-src/ext/bcmath/tests/*.phpt tests/php-src/
        cp php-src/ext/bcmath/tests/*.inc tests/php-src/

    - name: Run php-src BCMath tests
      run: ./scripts/run-php-src-tests.sh
