# github action that checks code with Rector
name: Rector

on:
    pull_request: null

jobs:
    rector:
        runs-on: ubuntu-latest
        if: github.event.pull_request.head.repo.full_name == 'nanasess/bcmath-polyfill'
        steps:
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            -
                uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f" # v3

            -   run: vendor/bin/rector --ansi
            # @todo apply coding standard if used

            -
                # commit only to core contributors who have repository access
                uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
                with:
                    commit_message: '[rector] Rector fixes'
                    commit_author: 'GitHub Action <actions@github.com>'
                    commit_user_email: 'action@github.com'
