# github action that checks code with Rector
name: Rector

on:
    pull_request: null

jobs:
    rector:
        runs-on: ubuntu-latest
        if: github.event.pull_request.head.repo.full_name == 'nanasess/bcmath-polyfill'
        steps:
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            -
                uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v3

            -   run: vendor/bin/rector --ansi
            # @todo apply coding standard if used

            -
                # commit only to core contributors who have repository access
                uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
                with:
                    commit_message: '[rector] Rector fixes'
                    commit_author: 'GitHub Action <actions@github.com>'
                    commit_user_email: 'action@github.com'
